apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:usJviQC/slavW1JyrpRf2SvbZcpVqzxmPIizpULDRJRFLeZIn6DdqdyctMR+6Wbcmky4YDUcmK5eLVDLKBtGm+uRgJMBVSn1nvOoa6faKAegwHsEoabqCjLGHpovUTqUjbBviaIQiNXlYj+GPqfuTbQCWGExQF1zaunjWs066gh4mFCNA0s/diJse3GFRdcZ+QkCJeVXF0JngQwTdpylTv5dZyabiUwMs+5t7JaEdhWVplengXaSD9WFgB9sgTZveSF3ckUL61/Tg5NvHjo6SZjZArSiEiWQ,iv:ZalKbaQ55skAkkeKNYfhdz3q2Q2I2AO9Nk0lHvFImXw=,tag:C6kW9h1wK1MHRxcVm5ICQQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168600l7a8wufzurhu9rvz8azddf3ac265jyzx8lmfac5jrrl2p8sgu2qy7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaE1adEN5a3JBY0ZTMnZj
            ZXZVdWljUXVLMlFkT1pydC9UQmkvSHpSR0NjCjc2WnlLeFhoS1ZCRkdMRXFrd3c4
            KzAvYmdHQThrZnpaTHdHL0l2aTFOUFkKLS0tIGloOTJmUnhNalhkRGdrZUxFZWU2
            c0tySXpVOENaUi9Vb3d3Njh4WGR4amcKjNnyRtdlR9F7aEAFUv88fF5WlewpabAm
            UMduVoUHPXtuHbyDPGyopckSHYtVYdEFDSaF9i99z1YkpSBzXSlGzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-12T13:18:59Z"
    mac: ENC[AES256_GCM,data:UawOCV2KhFOsSaiCuROFP4Lwe5aFS64VMU/QAayXZ+GQw0iLIUx5NBqtbSE1F0BArUbC3tsHr+neinqf0C1a8O9piy/wyH3qSeGgji/e39Zjc+ys4+EGQqLFQlncfYtKlwxCQlwTuFn1jw79AqGJ8nJ7ehng8qmv0mHp3iA/qOY=,iv:gMDVT9vfwq0lP+ciaYBZjizscVxVvFZKd0WAj1u272A=,tag:UPj8JZUxtX9urtfpnFTs1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
