apiVersion: v1
data:
    password: ENC[AES256_GCM,data:5WMulkdt+K4+QQby,iv:FKMlHGJUuoSLdgw7YORpJZovcCWuetbKrsV7vyniyFQ=,tag:UcH/AXzioWpNCbu25Hu/+A==,type:str]
    user: ENC[AES256_GCM,data:hUySVEjfrTg=,iv:CkA76I58JX0xmoMT8gCUBUtYqIxovV2NAlz4SuBX4wA=,tag:5BBvmLwlg4bc29YDbNU85Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vq9hlpu429sqeyhnpujv5v7e9xtakfrjsqprtnjpwzrft4fcqg6s654h84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WXIyTFprY2tQSDFjdFNt
            K0xJK09TRnByaC9WWDZnTTh4aWpvelpPYzA0ClFXOG5ia1VGN1dVSCs0TkI4NDhu
            WlNzRENTakF5WE9nZEF2NnRxaHZxSjQKLS0tIEw1NGg1bWdTcWZZRzh3b2sxaEkz
            R3NRdGlWTFpJNnFDdmsyVDc5T0dHQ1UKJbvKD405NjUNhA+OwDxzlLradnreqGw0
            myEEnnomUBIjDr05+fR7M3Bq59FXV/30TZg7/san1voigu/g/RNxzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T16:22:54Z"
    mac: ENC[AES256_GCM,data:+noWdIWLkjpTtB5EawXPCRqvV+85bUdzztOx4SVq1wV8/fSPC9wTlaPwtDc3Nlha57t290M+qCNKSeAqfC3DyQZ5eiEuG8MybrJvIiqKUnUD4cGRBeV0nb0mEmjcXk7N5DPhrkkvciEF9wzKgoP931v4JtQjFS8lFXI3lrrFgcU=,iv:3BG9AkRe4WXjnpZH0IBFw1rj7KpMVv0ICOBXeMz9AeA=,tag:ZGL+DiBKUmVCZjma+JTXEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
