apiVersion: v1
data:
    server: ENC[AES256_GCM,data:LwZkHy1lNAgh0VGNe67FR/S8pfYbz36gAQ6/J7R3ittiMDUx9IkczZcXsmeJaznP,iv:War0YvN1UwJJ9kfzXWAELbsmJXNPHwq24RKCDMa/hAw=,tag:9FRD/h9bUs5cmPE8S0atxw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kube-apiserver
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vq9hlpu429sqeyhnpujv5v7e9xtakfrjsqprtnjpwzrft4fcqg6s654h84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR3ByNW5yUkRTb1pXd1RZ
            Z1RlQnlFa3V1bVZZZGJ0SGRYTlJnWVhMeUVJCk8relhXSWpzRmFMQmd4SjZqbVlQ
            Zi9iZnlWOEcvRFhlWXRtSE5ydTdISU0KLS0tICtSV2FGQ2ZqbUpXRnJJT0wxano4
            ejczVXBxRUV1c1ZDOEJxOTg4QXJIcU0KuwINuHhkgm4ZfcuqukR7z3Y3IHCLJGne
            ZZB4Himqll7Pg1E7y/vVWkLD9mtAMS3Aui3biZCjn0L/mFV3lC9nCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T13:52:46Z"
    mac: ENC[AES256_GCM,data:WYQPBCuWI9Nvj1Ni3nFE/KTZY7cs5jCflnADjcrgjOV3VGIhtgulk+cfVJjJ9D7GH0sRWvTPHv1zaY+RKZc5GiT2rPB1yE3UW2WSZNfZ+ec1XGfQdaoOEvg6JFMQOzXsQtitYcEbOSF/5VfV+/n3oH/ixzRJ3ssMHDOk99o1OaQ=,iv:Hgh9jNEt2FZBdSDbBs9kSdWf7pF4wN9MsRRR9OSBpCI=,tag:nS4hVqvMT/pcq0EVRMBO0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
