apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      version: 35.0.0
  interval: 12h
  values:
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    podSecurityContext:
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
  valuesFrom:
    - kind: ConfigMap
      name: traefik-configmap
      valuesKey: traefik-chart-values.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
  namespace: traefik
data:
  traefik-chart-values.yaml: |
    additionalArguments:
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --entrypoints.websecure.http.tls.domains[0].main=javiercastano.xyz
      - --entrypoints.websecure.http.tls.domains[0].sans=*.javiercastano.xyz
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=software.development.tests@outlook.com
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
      - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    env:
      - name: CLOUDFLARE_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            key: dnsApiToken
            name: cloudflare-api-credentials
    ingressRoute:
      dashboard:
        enabled: true
    persistence:
      enabled: true
      existingClaim: traefik-cert-pvc
      path: /certs
      size: 128Mi
    # service:
    #   type: NodePort
      # spec:
      #   ports:
      #     - name: web
      #       port: 80
      #       nodePort: 30080
      #     - name: websecure
      #       port: 443
      #       nodePort: 30443