apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-cert-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/data/traefik-certs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homelabserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-cert-pvc
  namespace: traefik
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi