apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/traefik/
  - cloudflare-secret.yaml

patchesStrategicMerge:
  - traefik-patch.yaml

# patches:
#   - path: traefik-patch.yaml
#     target:
#       kind: HelmRelease
#       name: traefik
